/**
 * Research price discovery batch #2 — mass multi-source price observations.
 * All are DISCOVERED/REPORTED — NOT VERIFIED.
 */

export type ResearchPriceObservation = {
  sourceName: string;
  sourceTier: "secondary_automotive_media" | "secondary_automotive_reference";
  sourceUrl: string;
  articleTitle: string;
  publicationDate: string | null;
  manufacturer: string;
  model: string;
  variant: string;
  reportedPrice: number;
  priceText: string;
  priceType: "official" | "launch" | "special" | "campaign" | "starting_from" | "unknown";
  market: string;
  modelYear: string | null;
  sourceExcerpt: string;
  retrievalTimestamp: string;
};

export const BATCH2_OBSERVATIONS: ResearchPriceObservation[] = [
  // === HEADLIGHT MAGAZINE (pages 3-8) ===
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-ford-ranger-wolftrak-2026/",
    articleTitle: "Official Price: Ford Ranger Wolftrak 2026", publicationDate: null,
    manufacturer: "Ford", model: "Ranger", variant: "Wolftrak",
    reportedPrice: 1089000, priceText: "1,089,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Ford Ranger Wolftrak ราคา 1,089,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-lepas-l6/",
    articleTitle: "Official Price: Lepas L6", publicationDate: null,
    manufacturer: "Lepas", model: "L6", variant: "Standard",
    reportedPrice: 799900, priceText: "799,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Lepas L6 ราคา 799,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-civic-ehev-2026-s-plus-shift/",
    articleTitle: "Official Price: Honda Civic e:HEV 2026 S+ Shift", publicationDate: null,
    manufacturer: "Honda", model: "Civic", variant: "e:HEV S+ Shift",
    reportedPrice: 1259000, priceText: "1,259,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Honda Civic e:HEV S+ Shift ราคา 1,259,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-byd-seal-6-2026/",
    articleTitle: "Official Price: BYD Seal 6 2026", publicationDate: null,
    manufacturer: "BYD", model: "Seal 6", variant: "Premium",
    reportedPrice: 949900, priceText: "949,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Seal 6 Premium ราคา 949,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-byd-sealion-5-dm-i-super-phev/",
    articleTitle: "Official Price: BYD Sealion 5 DM-i Super PHEV", publicationDate: null,
    manufacturer: "BYD", model: "Sealion 5", variant: "DM-i Super PHEV",
    reportedPrice: 799900, priceText: "799,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Sealion 5 DM-i Super PHEV ราคา 799,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-suzuki-carry-my2026/",
    articleTitle: "Official Price: Suzuki Carry MY2026", publicationDate: null,
    manufacturer: "Suzuki", model: "Carry", variant: "Standard",
    reportedPrice: 375000, priceText: "375,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Suzuki Carry MY2026 ราคา 375,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-avatr-11-my2026/",
    articleTitle: "Official Price: Avatr 11 MY2026", publicationDate: null,
    manufacturer: "Avatr", model: "11", variant: "Standard",
    reportedPrice: 2899000, priceText: "2,899,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Avatr 11 MY2026 ราคา 2,899,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-mitsubishi-attrage-my2026/",
    articleTitle: "Official Price: Mitsubishi Attrage MY2026", publicationDate: null,
    manufacturer: "Mitsubishi", model: "Attrage", variant: "Standard",
    reportedPrice: 619000, priceText: "619,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Mitsubishi Attrage MY2026 ราคา 619,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-city-big-minorchange-2026/",
    articleTitle: "Official Price: Honda City Big Minorchange 2026", publicationDate: null,
    manufacturer: "Honda", model: "City", variant: "Big MC",
    reportedPrice: 749000, priceText: "749,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Honda City Big MC 2026 ราคา 749,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-mg-urban-2026/",
    articleTitle: "Official Price: MG URBAN 2026", publicationDate: null,
    manufacturer: "MG", model: "URBAN", variant: "MAX",
    reportedPrice: 709900, priceText: "709,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG URBAN MAX ราคา 709,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-changan-nevo-q05/",
    articleTitle: "Official Price: Changan Nevo Q05", publicationDate: null,
    manufacturer: "Changan", model: "Nevo Q05", variant: "Standard",
    reportedPrice: 679900, priceText: "679,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Changan Nevo Q05 ราคา 679,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-accord-2026/",
    articleTitle: "Official Price: Honda Accord 2026", publicationDate: null,
    manufacturer: "Honda", model: "Accord", variant: "e:HEV RS",
    reportedPrice: 1764000, priceText: "1,764,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Honda Accord e:HEV RS ราคา 1,764,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-suzuki-jimny-with-safety-support-my2026/",
    articleTitle: "Official Price: Suzuki Jimny MY2026", publicationDate: null,
    manufacturer: "Suzuki", model: "Jimny", variant: "Standard",
    reportedPrice: 1620000, priceText: "1,620,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Suzuki Jimny MY2026 ราคา 1,620,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-mg4-my2026-2/",
    articleTitle: "Official Price: MG4 MY2026", publicationDate: null,
    manufacturer: "MG", model: "MG4", variant: "Standard",
    reportedPrice: 699900, priceText: "699,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG4 Standard ราคา 699,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-mg-im-5-long-range-rwd/",
    articleTitle: "Official Price: MG IM-5 Long Range RWD", publicationDate: null,
    manufacturer: "MG", model: "IM5", variant: "Long Range RWD",
    reportedPrice: 1449900, priceText: "1,449,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG IM-5 Long Range RWD ราคา 1,449,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-nio-firefly/",
    articleTitle: "Official Price: NIO Firefly", publicationDate: null,
    manufacturer: "NIO", model: "Firefly", variant: "Standard",
    reportedPrice: 799000, priceText: "799,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "NIO Firefly ราคา 799,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-tesla-model-y-l-long-wheelbase/",
    articleTitle: "Official Price: Tesla Model Y L Long Wheelbase", publicationDate: null,
    manufacturer: "Tesla", model: "Model Y", variant: "L Long Wheelbase",
    reportedPrice: 1999000, priceText: "1,999,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Tesla Model Y L ราคา 1,999,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/2026-03-23-official-price-byd-atto1/",
    articleTitle: "Official Price: BYD Atto 1", publicationDate: "2026-03-23",
    manufacturer: "BYD", model: "Atto 1", variant: "Premium",
    reportedPrice: 459900, priceText: "459,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Atto 1 Premium ราคา 459,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-geely-ex5-my2026/",
    articleTitle: "Official Price: Geely EX5 MY2026", publicationDate: null,
    manufacturer: "Geely", model: "EX5", variant: "Standard",
    reportedPrice: 899000, priceText: "899,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Geely EX5 MY2026 ราคา 899,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-nissan-kicks-e-power-minorchange-2026/",
    articleTitle: "Official Price: Nissan Kicks e-Power MC 2026", publicationDate: null,
    manufacturer: "Nissan", model: "Kicks", variant: "e-Power",
    reportedPrice: 899900, priceText: "899,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Nissan Kicks e-Power ราคา 899,900 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-en2/",
    articleTitle: "Official Price: Honda e:N2", publicationDate: null,
    manufacturer: "Honda", model: "e:N2", variant: "EV",
    reportedPrice: 1429000, priceText: "1,429,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Honda e:N2 ราคา 1,429,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-lexus-is-300h-minorchange-2026/",
    articleTitle: "Official Price: Lexus IS 300h MC 2026", publicationDate: null,
    manufacturer: "Lexus", model: "IS", variant: "300h",
    reportedPrice: 3099000, priceText: "3,099,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Lexus IS 300h ราคา 3,099,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-hyundai-santa-fe-my2026/",
    articleTitle: "Official Price: Hyundai Santa Fe MY2026", publicationDate: null,
    manufacturer: "Hyundai", model: "Santa Fe", variant: "Standard",
    reportedPrice: 1799000, priceText: "1,799,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Hyundai Santa Fe MY2026 ราคา 1,799,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-gwm-ora-5-hev/",
    articleTitle: "Official Price: GWM ORA 5 HEV", publicationDate: null,
    manufacturer: "GWM", model: "ORA 5", variant: "HEV",
    reportedPrice: 799000, priceText: "799,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "GWM ORA 5 HEV ราคา 799,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-subaru-crosstrek/",
    articleTitle: "Official Price: Subaru Crosstrek", publicationDate: null,
    manufacturer: "Subaru", model: "Crosstrek", variant: "Standard",
    reportedPrice: 2350000, priceText: "2,350,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Subaru Crosstrek ราคา 2,350,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-ford-everest-platinum-my2026/",
    articleTitle: "Official Price: Ford Everest Platinum MY2026", publicationDate: null,
    manufacturer: "Ford", model: "Everest", variant: "Platinum",
    reportedPrice: 2284000, priceText: "2,284,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Ford Everest Platinum MY2026 ราคา 2,284,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-ford-ranger-wildtrak-x-my2026/",
    articleTitle: "Official Price: Ford Ranger Wildtrak X MY2026", publicationDate: null,
    manufacturer: "Ford", model: "Ranger", variant: "Wildtrak X",
    reportedPrice: 1469000, priceText: "1,469,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Ford Ranger Wildtrak X MY2026 ราคา 1,469,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-mazda-6e-edit/",
    articleTitle: "Official Price: Mazda 6e", publicationDate: null,
    manufacturer: "Mazda", model: "6e", variant: "Standard",
    reportedPrice: 1199000, priceText: "1,199,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Mazda 6e ราคา 1,199,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-toyota-land-cruiser-fj/",
    articleTitle: "Official Price: Toyota Land Cruiser FJ", publicationDate: null,
    manufacturer: "Toyota", model: "Land Cruiser FJ", variant: "Standard",
    reportedPrice: 1269000, priceText: "1,269,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Toyota Land Cruiser FJ ราคา 1,269,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-bmw-ix3-na5/",
    articleTitle: "Official Price: BMW iX3 NA5", publicationDate: null,
    manufacturer: "BMW", model: "iX3", variant: "NA5",
    reportedPrice: 3599000, priceText: "3,599,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BMW iX3 NA5 ราคา 3,599,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-zeekr-x-my-2026/",
    articleTitle: "Official Price: Zeekr X MY2026", publicationDate: null,
    manufacturer: "Zeekr", model: "X", variant: "Standard",
    reportedPrice: 1069000, priceText: "1,069,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Zeekr X MY2026 ราคา 1,069,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-toyota-corolla-altis-my2026/",
    articleTitle: "Official Price: Toyota Corolla Altis MY2026", publicationDate: null,
    manufacturer: "Toyota", model: "Corolla Altis", variant: "Standard",
    reportedPrice: 1129000, priceText: "1,129,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Toyota Corolla Altis MY2026 ราคา 1,129,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/special-price-kia-carnival-sxl-diesel-11-seats-2026/",
    articleTitle: "Special Price: Kia Carnival SXL Diesel 2026", publicationDate: null,
    manufacturer: "Kia", model: "Carnival", variant: "SXL Diesel",
    reportedPrice: 2019000, priceText: "2,019,000", priceType: "special", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Kia Carnival SXL Diesel ราคาพิเศษ 2,019,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/special-price-suzuki-fronx-august-2026/",
    articleTitle: "Special Price: Suzuki Fronx August 2026", publicationDate: "2026-08",
    manufacturer: "Suzuki", model: "Fronx", variant: "Standard",
    reportedPrice: 649000, priceText: "649,000", priceType: "special", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Suzuki Fronx ราคาพิเศษ 649,000 บาท", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  // === 9CARTHAI (Honda full price table) ===
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "Civic", variant: "e:HEV EL",
    reportedPrice: 949000, priceText: "949,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Civic e:HEV EL ราคา 949,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "Civic", variant: "e:HEV EL+",
    reportedPrice: 1109000, priceText: "1,109,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Civic e:HEV EL+ ราคา 1,109,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "Civic", variant: "e:HEV RS",
    reportedPrice: 1259000, priceText: "1,259,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Civic e:HEV RS ราคา 1,259,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "Civic", variant: "Type R",
    reportedPrice: 3990000, priceText: "3,990,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Civic Type R ราคา 3,990,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "HR-V", variant: "e:HEV E",
    reportedPrice: 899000, priceText: "899,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "HR-V e:HEV E ราคา 899,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "HR-V", variant: "e:HEV EL",
    reportedPrice: 1079000, priceText: "1,079,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "HR-V e:HEV EL ราคา 1,079,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "HR-V", variant: "e:HEV RS",
    reportedPrice: 1179000, priceText: "1,179,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "HR-V e:HEV RS ราคา 1,179,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "WR-V", variant: "SV",
    reportedPrice: 799000, priceText: "799,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "WR-V รุ่น SV ราคา 799,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "WR-V", variant: "RS",
    reportedPrice: 869000, priceText: "869,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "WR-V รุ่น RS ราคา 869,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "Accord", variant: "e:HEV E",
    reportedPrice: 1479000, priceText: "1,479,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Accord รุ่น e:HEV E 1,479,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "Accord", variant: "e:HEV EL",
    reportedPrice: 1629000, priceText: "1,629,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Accord รุ่น e:HEV EL ราคา 1,629,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "Accord", variant: "e:HEV RS",
    reportedPrice: 1764000, priceText: "1,764,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Accord รุ่น e:HEV RS ราคา 1,764,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  // === 9CARTHAI (Toyota full price table) ===
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Camry", variant: "HEV Smart",
    reportedPrice: 1475000, priceText: "1,475,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Camry Hybrid รุ่น HEV SMART ราคา 1,475,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Camry", variant: "HEV Premium",
    reportedPrice: 1659000, priceText: "1,659,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Camry Hybrid รุ่น HEV PREMIUM ราคา 1,659,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Camry", variant: "HEV Premium Luxury",
    reportedPrice: 1809000, priceText: "1,809,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Camry Hybrid รุ่น HEV PREMIUM LUXURY ราคา 1,809,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris", variant: "Sport AT",
    reportedPrice: 584000, priceText: "584,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris รุ่น Sport AT ราคา 584,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris", variant: "Smart AT",
    reportedPrice: 644000, priceText: "644,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris รุ่น Smart AT ราคา 644,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris", variant: "Sport Premium AT",
    reportedPrice: 689000, priceText: "689,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris รุ่น Sport Premium AT ราคา 689,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris Ativ HEV", variant: "Premium",
    reportedPrice: 719000, priceText: "719,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris ATIV HEV รุ่น Premium ราคา 719,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris Ativ HEV", variant: "GR Sport",
    reportedPrice: 769000, priceText: "769,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris ATIV HEV รุ่น GR SPORT ราคา 769,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris Cross", variant: "HEV Smart",
    reportedPrice: 789000, priceText: "789,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris Cross HEV Smart ราคา 789,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris Cross", variant: "HEV Premium",
    reportedPrice: 849000, priceText: "849,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris Cross HEV Premium ราคา 849,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris Cross", variant: "HEV Premium Luxury",
    reportedPrice: 899000, priceText: "899,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris Cross HEV Premium Luxury ราคา 899,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Yaris Cross", variant: "HEV NightShade",
    reportedPrice: 919000, priceText: "919,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Yaris Cross HEV NightShade ราคา 919,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  // === 9CARTHAI (BYD full price table) ===
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Atto 1", variant: "Dynamic",
    reportedPrice: 429900, priceText: "429,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD ATTO 1 รุ่น Dynamic ราคา 429,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Atto 2", variant: "Dynamic",
    reportedPrice: 629900, priceText: "629,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD ATTO 2 รุ่น Dynamic ราคา 629,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Atto 3", variant: "Premium",
    reportedPrice: 669900, priceText: "669,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD ATTO 3 410 Premium ราคา 669,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Atto 3", variant: "Extended Range",
    reportedPrice: 769900, priceText: "769,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD ATTO 3 Extended Range ราคา 769,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "M6", variant: "Dynamic 6 Seats",
    reportedPrice: 799900, priceText: "799,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD M6 Dynamic 6 Seats ราคา 799,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "M6", variant: "Extended 6 Seats",
    reportedPrice: 899900, priceText: "899,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD M6 Extended 6 Seats ราคา 899,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Seal 6", variant: "Standard",
    reportedPrice: 799900, priceText: "799,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD SEAL 6 รุ่น Standard ราคา 799,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Seal 6", variant: "Dynamic",
    reportedPrice: 899900, priceText: "899,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD SEAL 6 รุ่น Dynamic ราคา 899,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Seal 6", variant: "Premium",
    reportedPrice: 949900, priceText: "949,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD SEAL 6 รุ่น Premium ราคา 949,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Sealion 5", variant: "DM-i Dynamic",
    reportedPrice: 759900, priceText: "759,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD SEALION 5 DM-i รุ่น Dynamic ราคา 759,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Sealion 5", variant: "DM-i Premium",
    reportedPrice: 799900, priceText: "799,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD SEALION 5 DM-i รุ่น Premium ราคา 799,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Sealion 6", variant: "Dynamic",
    reportedPrice: 939900, priceText: "939,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD SEALION 6 รุ่น Dynamic ราคา 939,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/byd-price/",
    articleTitle: "BYD Car Price List Thailand", publicationDate: null,
    manufacturer: "BYD", model: "Sealion 6", variant: "Premium",
    reportedPrice: 1039900, priceText: "1,039,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD SEALION 6 รุ่น Premium ราคา 1,039,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  // === 9CARTHAI (MG full price table) ===
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "MG3", variant: "Hybrid+ D",
    reportedPrice: 579900, priceText: "579,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG3 Hybrid+ D 579,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "MG3", variant: "Hybrid+ X",
    reportedPrice: 619900, priceText: "619,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG3 Hybrid+ X 619,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "MG5", variant: "10th Anniversary",
    reportedPrice: 589900, priceText: "589,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG5 1.5 รุ่น ครบรอบ 10 ปี ราคา 589,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "MG5", variant: "PRO D",
    reportedPrice: 629900, priceText: "629,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG5 1.5 รุ่น PRO D ราคา 629,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "MG5", variant: "PRO X",
    reportedPrice: 669900, priceText: "669,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG5 1.5 รุ่น PRO X ราคา 669,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "IM6", variant: "Premium 2WD",
    reportedPrice: 1399900, priceText: "1,399,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG IM6 (Premium 2WD) ราคา 1,399,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "IM6", variant: "Performance AWD",
    reportedPrice: 1799900, priceText: "1,799,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG IM6 (Performance AWD) ราคา 1,799,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "Cyberster", variant: "Standard",
    reportedPrice: 2499000, priceText: "2,499,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG Cyberster ราคา 2,499,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "EP", variant: "Standard",
    reportedPrice: 761000, priceText: "761,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG EP รุ่น Standard 761,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "EP Plus", variant: "Standard",
    reportedPrice: 771000, priceText: "771,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG EP PLUS ราคา 771,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "ES", variant: "Standard",
    reportedPrice: 959000, priceText: "959,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG ES ราคา 959,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "HS", variant: "PHEV D",
    reportedPrice: 1299000, priceText: "1,299,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG HS PHEV รุ่น D 1,299,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "HS", variant: "PHEV X",
    reportedPrice: 1379000, priceText: "1,379,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG HS PHEV รุ่น X 1,379,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  // === AUTOSPINN (BYD price table) ===
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Dolphin", variant: "Standard",
    reportedPrice: 509900, priceText: "509,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Dolphin Standard = 509,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Dolphin", variant: "Extended",
    reportedPrice: 599900, priceText: "599,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Dolphin Extended = 599,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Seal", variant: "Dynamic",
    reportedPrice: 1325000, priceText: "1,325,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Seal Dynamic = 1,325,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Seal", variant: "Premium",
    reportedPrice: 1449000, priceText: "1,449,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Seal Premium = 1,449,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Seal", variant: "AWD Performance",
    reportedPrice: 1599000, priceText: "1,599,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Seal AWD Performance = 1,599,000", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Seal 5", variant: "DM-i Standard",
    reportedPrice: 599900, priceText: "599,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Seal 5 DM-i Standard = 599,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Seal 5", variant: "DM-i Dynamic",
    reportedPrice: 659900, priceText: "659,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Seal 5 DM-i Dynamic = 659,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Seal 5", variant: "DM-i Premium",
    reportedPrice: 699900, priceText: "699,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Seal 5 DM-i Premium = 699,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Sealion 6", variant: "Dynamic",
    reportedPrice: 859900, priceText: "859,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Sealion 6 Dynamic = 859,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
  {
    sourceName: "AutoSpinn", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.autospinn.com/2026/03/byd-price-updated-148444",
    articleTitle: "BYD Price Updated March 2026", publicationDate: "2026-03",
    manufacturer: "BYD", model: "Sealion 6", variant: "Premium",
    reportedPrice: 899900, priceText: "899,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Sealion 6 Premium = 899,900", retrievalTimestamp: "2026-09-17T13:00:00Z",
  },
];
