/**
 * Batch #3 research observations — new sources: AutoLifeThailand, Car2Day.
 */

import type { ResearchPriceObservation } from "./research-observations";

export const BATCH3_OBSERVATIONS: ResearchPriceObservation[] = [
  // === AUTOLIFETHAILAND ===
  {
    sourceName: "AutoLifeThailand", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://autolifethailand.tv/official-special-price-byd-seal-5-dm-i-phev-plug-in-hybrid-sep-2026/",
    articleTitle: "Official Special Price: BYD Seal 5 DM-i PHEV September 2026",
    publicationDate: "2026-09",
    manufacturer: "BYD", model: "Seal 5", variant: "DM-i PHEV",
    reportedPrice: 649900, priceText: "649,900", priceType: "special", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Seal 5 DM-i PHEV ราคาพิเศษ 649,900 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "AutoLifeThailand", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://autolifethailand.tv/official-price-discount-byd-sealion-5-dm-i-phev-sep-2026/",
    articleTitle: "Official Price Discount: BYD Sealion 5 DM-i PHEV September 2026",
    publicationDate: "2026-09",
    manufacturer: "BYD", model: "Sealion 5", variant: "DM-i PHEV",
    reportedPrice: 744900, priceText: "744,900", priceType: "special", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Sealion 5 DM-i PHEV ราคาลด 744,900 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "AutoLifeThailand", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://autolifethailand.tv/offcial-price-denza-z9gt-ev-bev-thailand-2026/",
    articleTitle: "Official Price: Denza Z9GT EV BEV Thailand 2026",
    publicationDate: null,
    manufacturer: "Denza", model: "Z9GT", variant: "Standard",
    reportedPrice: 2899900, priceText: "2,899,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Denza Z9GT EV BEV ราคา 2,899,900 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "AutoLifeThailand", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://autolifethailand.tv/official-price-discount-byd-atto-2-ev-bev-sep-2026/",
    articleTitle: "Official Price Discount: BYD Atto 2 EV BEV September 2026",
    publicationDate: "2026-09",
    manufacturer: "BYD", model: "Atto 2", variant: "EV BEV",
    reportedPrice: 569900, priceText: "569,900", priceType: "special", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BYD Atto 2 EV BEV ราคาลด 569,900 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "AutoLifeThailand", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://autolifethailand.tv/official-price-tesla-model-y-thailand/",
    articleTitle: "Official Price: Tesla Model Y Thailand",
    publicationDate: null,
    manufacturer: "Tesla", model: "Model Y", variant: "Standard",
    reportedPrice: 2509000, priceText: "2,509,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Tesla Model Y ราคา 2,509,000 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "AutoLifeThailand", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://autolifethailand.tv/official-price-tesla-model-3-official-thailand/",
    articleTitle: "Official Price: Tesla Model 3 Thailand",
    publicationDate: null,
    manufacturer: "Tesla", model: "Model 3", variant: "Standard",
    reportedPrice: 2309000, priceText: "2,309,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Tesla Model 3 ราคา 2,309,000 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  // === HEADLIGHT ADDITIONAL ===
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-civic-ehev-2026-s-plus-shift/",
    articleTitle: "Official Price: Honda Civic e:HEV 2026 S+ Shift", publicationDate: null,
    manufacturer: "Honda", model: "Civic", variant: "e:HEV S+",
    reportedPrice: 1259000, priceText: "1,259,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Honda Civic e:HEV S+ Shift ราคา 1,259,000 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-city-big-minorchange-2026/",
    articleTitle: "Official Price: Honda City Big MC 2026", publicationDate: null,
    manufacturer: "Honda", model: "City", variant: "Big MC",
    reportedPrice: 749000, priceText: "749,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Honda City Big MC 2026 ราคา 749,000 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-accord-2026/",
    articleTitle: "Official Price: Honda Accord 2026", publicationDate: null,
    manufacturer: "Honda", model: "Accord", variant: "e:HEV RS",
    reportedPrice: 1764000, priceText: "1,764,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Honda Accord e:HEV RS ราคา 1,764,000 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-en2/",
    articleTitle: "Official Price: Honda e:N2", publicationDate: null,
    manufacturer: "Honda", model: "e:N2", variant: "EV",
    reportedPrice: 1429000, priceText: "1,429,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Honda e:N2 ราคา 1,429,000 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine", sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-toyota-corolla-altis-my2026/",
    articleTitle: "Official Price: Toyota Corolla Altis MY2026", publicationDate: null,
    manufacturer: "Toyota", model: "Corolla Altis", variant: "Standard",
    reportedPrice: 1129000, priceText: "1,129,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Toyota Corolla Altis MY2026 ราคา 1,129,000 บาท", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  // === 9CARTHAI ADDITIONAL (more variants) ===
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Fortuner", variant: "2.5G MT 2WD",
    reportedPrice: 1104000, priceText: "1,104,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Fortuner โตโยต้า ฟอร์จูนเนอร์ 2.5G MT 2WD 1,104,000", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/toyota-price/",
    articleTitle: "Toyota Car Price List Thailand", publicationDate: null,
    manufacturer: "Toyota", model: "Fortuner", variant: "2.5V AT 2WD",
    reportedPrice: 1209000, priceText: "1,209,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "Fortuner โตโยต้า ฟอร์จูนเนอร์ 2.5V AT 2WD 1,209,000", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "ZS EV", variant: "Standard",
    reportedPrice: 829900, priceText: "829,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG ZS EV ราคา 829,900", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/mg-price/",
    articleTitle: "MG Car Price List Thailand", publicationDate: null,
    manufacturer: "MG", model: "MG4", variant: "Standard",
    reportedPrice: 699900, priceText: "699,900", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "MG4 Standard ราคา 699,900", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "City Hatchback", variant: "Standard",
    reportedPrice: 579000, priceText: "579,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "City Hatchback ฮอนด้า ซิตี้ แฮทช์แบ็ก 579,000", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "CR-V", variant: "e:HEV E",
    reportedPrice: 1249000, priceText: "1,249,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "CR-V e:HEV E ราคา 1,249,000", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "CR-V", variant: "e:HEV RS",
    reportedPrice: 1409000, priceText: "1,409,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "CR-V e:HEV RS ราคา 1,409,000", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
  {
    sourceName: "9CARTHAI", sourceTier: "secondary_automotive_reference",
    sourceUrl: "https://www.9carthai.com/honda-price/",
    articleTitle: "Honda Car Price List Thailand", publicationDate: null,
    manufacturer: "Honda", model: "BR-V", variant: "Standard",
    reportedPrice: 915000, priceText: "915,000", priceType: "official", market: "Thailand", modelYear: "2026",
    sourceExcerpt: "BR-V ราคา 915,000", retrievalTimestamp: "2026-09-17T13:30:00Z",
  },
];
