/**
 * Research price discovery batch — secondary-source price observations from Thai automotive publications.
 * 
 * These are REPORTED/UNVERIFIED observations — NOT verified catalog prices.
 * They do NOT set Price.sourceDocumentId and do NOT enter currentOfficialPrice.
 * They are stored as research candidates for later reconciliation.
 */

export type ResearchPriceObservation = {
  sourceName: string;
  sourceTier: "primary_official" | "secondary_automotive_media" | "tertiary_listing";
  sourceUrl: string;
  articleTitle: string;
  publicationDate: string | null;
  manufacturer: string;
  model: string;
  variant: string;
  reportedPrice: number;
  priceText: string;
  priceType: "official" | "launch" | "special" | "campaign" | "starting_from" | "unknown";
  market: string;
  modelYear: string | null;
  sourceExcerpt: string;
  retrievalTimestamp: string;
};

export const RESEARCH_OBSERVATIONS: ResearchPriceObservation[] = [
  // HeadLight Magazine — official price articles
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-denza-z9gt/",
    articleTitle: "Official Price: Denza Z9GT",
    publicationDate: null,
    manufacturer: "Denza",
    model: "Z9GT",
    variant: "Standard",
    reportedPrice: 2899900,
    priceText: "2,899,900",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Denza Z9GT ราคา 2,899,900 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-hyundai-staria-hybrid-minorchange-2026/",
    articleTitle: "Official Price: Hyundai Staria Hybrid Minorchange 2026",
    publicationDate: null,
    manufacturer: "Hyundai",
    model: "Staria",
    variant: "Hybrid",
    reportedPrice: 2399000,
    priceText: "2,399,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Hyundai Staria Hybrid ราคา 2,399,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-toyota-land-cruiser-fj-2/",
    articleTitle: "Official Price: Toyota Land Cruiser FJ",
    publicationDate: null,
    manufacturer: "Toyota",
    model: "Land Cruiser FJ",
    variant: "Standard",
    reportedPrice: 1289000,
    priceText: "1,289,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Toyota Land Cruiser FJ ราคา 1,289,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-hyundai-ioniq-5-n-line-ckd-thailand-2nd-lot/",
    articleTitle: "Official Price: Hyundai Ioniq 5 N Line CKD Thailand 2nd Lot",
    publicationDate: null,
    manufacturer: "Hyundai",
    model: "Ioniq 5",
    variant: "N Line",
    reportedPrice: 1449000,
    priceText: "1,449,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Hyundai Ioniq 5 N Line ราคา 1,449,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-byd-sealion-7-2026-awd-ultimate/",
    articleTitle: "Official Price: BYD Sealion 7 2026 AWD Ultimate",
    publicationDate: null,
    manufacturer: "BYD",
    model: "Sealion 7",
    variant: "AWD Ultimate",
    reportedPrice: 1349900,
    priceText: "1,349,900",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "BYD Sealion 7 AWD Ultimate ราคา 1,349,900 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-gwm-tank-500-diesel-2026/",
    articleTitle: "Official Price: GWM Tank 500 Diesel 2026",
    publicationDate: null,
    manufacturer: "GWM",
    model: "Tank 500",
    variant: "Diesel",
    reportedPrice: 1669000,
    priceText: "1,669,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "GWM Tank 500 Diesel ราคา 1,669,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-honda-super-one/",
    articleTitle: "Official Price: Honda Super-ONE",
    publicationDate: null,
    manufacturer: "Honda",
    model: "Super-ONE",
    variant: "EV",
    reportedPrice: 990000,
    priceText: "990,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Honda Super-ONE ราคา 990,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-geely-starray-em-r-reev/",
    articleTitle: "Official Price: Geely Starray EM-R REEV",
    publicationDate: null,
    manufacturer: "Geely",
    model: "Starray",
    variant: "EM-R REEV",
    reportedPrice: 1599000,
    priceText: "1,599,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Geely Starray EM-R REEV ราคา 1,599,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-toyota-alphard-vellfire-my2026/",
    articleTitle: "Official Price: Toyota Alphard/Vellfire MY2026",
    publicationDate: null,
    manufacturer: "Toyota",
    model: "Alphard",
    variant: "HEV",
    reportedPrice: 3599000,
    priceText: "3,599,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Toyota Alphard HEV ราคา 3,599,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-mini-aceman-collections-mini-aceman-collections-multitone-shadow-jcw/",
    articleTitle: "Official Price: MINI Aceman Collections",
    publicationDate: null,
    manufacturer: "MINI",
    model: "Aceman",
    variant: "Collections",
    reportedPrice: 2199000,
    priceText: "2,199,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "MINI Aceman Collections ราคา 2,199,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-kia-pv5-cargo/",
    articleTitle: "Official Price: Kia PV5 Cargo",
    publicationDate: null,
    manufacturer: "Kia",
    model: "PV5",
    variant: "Cargo",
    reportedPrice: 1499000,
    priceText: "1,499,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Kia PV5 Cargo ราคา 1,499,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/special-price-hyundai-palisade-august-2026/",
    articleTitle: "Special Price: Hyundai Palisade August 2026",
    publicationDate: "2026-08",
    manufacturer: "Hyundai",
    model: "Palisade",
    variant: "Standard",
    reportedPrice: 2499000,
    priceText: "2,499,000",
    priceType: "special",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Hyundai Palisade ราคาพิเศษ 2,499,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/special-price-suzuki-fronx-september-2026/",
    articleTitle: "Special Price: Suzuki Fronx September 2026",
    publicationDate: "2026-09",
    manufacturer: "Suzuki",
    model: "Fronx",
    variant: "Standard",
    reportedPrice: 699000,
    priceText: "699,000",
    priceType: "special",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Suzuki Fronx ราคาพิเศษ 699,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/unofficial-price-xpeng-l03/",
    articleTitle: "Unofficial Price: Xpeng L03",
    publicationDate: null,
    manufacturer: "Xpeng",
    model: "L03",
    variant: "Standard",
    reportedPrice: 899000,
    priceText: "899,000",
    priceType: "unknown",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Xpeng L03 ราคาประมาณ 899,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-lexus-es-2026_edit1/",
    articleTitle: "Official Price: Lexus ES 2026",
    publicationDate: null,
    manufacturer: "Lexus",
    model: "ES",
    variant: "Standard",
    reportedPrice: 2999000,
    priceText: "2,999,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Lexus ES ราคา 2,999,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
  {
    sourceName: "HeadLight Magazine",
    sourceTier: "secondary_automotive_media",
    sourceUrl: "https://www.headlightmag.com/official-price-toyota-coaster-my2026/",
    articleTitle: "Official Price: Toyota Coaster MY2026",
    publicationDate: null,
    manufacturer: "Toyota",
    model: "Coaster",
    variant: "Standard",
    reportedPrice: 2499000,
    priceText: "2,499,000",
    priceType: "official",
    market: "Thailand",
    modelYear: "2026",
    sourceExcerpt: "Toyota Coaster ราคา 2,499,000 บาท",
    retrievalTimestamp: "2026-09-17T12:30:00Z",
  },
];
